microsoft/vscode-maven

- package.json
> fix #16: update package.json

- package.json
- src/ArchetypeModule.ts
Related issue: #20 
Previous: List `org.apache.maven` and `com.microsoft.azure` archetypes first
Now: List top 10 most popular archetypes according to the real usage data.
> list top 10 popular archetypes first

- README.md
- package.json
- src/ProjectDataProvider.ts
> add new configuration to specify default mvn options

- src/ArchetypeModule.ts
update the list according to AI report.
Should not hard code and manually update in future.
e.g. update a file in Azure Storage, and set jenkins job to update the file regularly.
> update popular archetypes

- src/ProjectDataProvider.ts
- src/VSCodeUI.ts
- src/extension.ts
https://github.com/Microsoft/vscode-maven/commit/1bd4726503e44c4d0dbc03da6eac3a389e672fc3 for #41 
https://github.com/Microsoft/vscode-maven/commit/a1f7825e8eb95344256384176bb288561712bb9b for #42
> fix custom env related issues

- src/VSCodeUI.ts
> ignore possible error when deleting disposed terminal

- CHANGELOG.md
- package.json
- src/ProjectDataProvider.ts
- src/extension.ts
- src/model/WorkspaceItem.ts
> allow to invoke maven commands from command palette

- package-lock.json
- src/VSCodeUI.ts
- tslint.json
> format CWD for WSL Bash

- src/Utils.ts
- src/VSCodeUI.ts
> format filepath for WSL

- CHANGELOG.md
- package-lock.json
- package.json
> bump version to 0.9.0

- package.json
> change version to 0.10.0

- package-lock.json
- src/archetype/Archetype.ts
- src/archetype/ArchetypeModule.ts
> avoid to show duplicate archetypes

- src/extension.ts
> refresh explorer when workspace folders change

- package-lock.json
- src/VSCodeUI.ts
> use cmd /c to execute maven command in powershell

- TestPlan.md
- src/archetype/ArchetypeModule.ts
Switch order of the 2 steps. 
See: #122
> Select target folder after archetype is selected.

- CHANGELOG.md
- package-lock.json
- package.json
- src/VSCodeUI.ts
- thirdpartynotice.txt
Previous it opens the markdown file directly in VSCode, hard to search for what a user wants. 
Now it opens the page in browser.
> Open troubleshooting page in browser.

- TestPlan.md
- package-lock.json
- package.json
- src/Errors.ts
- src/archetype/ArchetypeModule.ts
- src/extension.ts
This PR group the statements into steps.
* OperationStep
* Info
> Track steps and archetype.

- package.json
- package.nls.json
- package.nls.zh.json
First step to localize command names. 
Related issue: #146
> Add Chinese localization for package.json

- src/archetype/ArchetypeModule.ts
> Fix a potential NPE.

- package-lock.json
- package.json
- src/VSCodeUI.ts
> Replace opn with vscode.open

- package.json
- package.nls.json
- package.nls.zh.json
- src/Utils.ts
- src/explorer/MavenExplorerProvider.ts
- src/explorer/model/ITreeItem.ts
- src/explorer/model/MavenPlugin.ts
- src/explorer/model/ModulesMenu.ts
- src/explorer/model/PluginGoal.ts
- src/extension.ts
> Allow to manually refresh plugin goals.

- src/Utils.ts
- src/explorer/MavenExplorerProvider.ts
- src/explorer/model/ITreeItem.ts
- src/explorer/model/MavenProject.ts
- src/explorer/model/ModulesMenu.ts
- src/explorer/model/PluginsMenu.ts
- src/explorer/model/WorkspaceFolder.ts
- src/extension.ts
1. Read calculated Effective-POM if possible. 
2. Add listeners to update Effective-POM automatically.
> Better UX for Effective POM. 

- src/Utils.ts
- src/explorer/model/ITreeItem.ts
- src/explorer/model/MavenPlugin.ts
- src/explorer/model/MavenProject.ts
- src/explorer/model/PluginsMenu.ts
- src/explorer/pluginInfoProvider.ts
- src/extension.ts
> Refine mechanism of refreshing item nodes.

- src/Utils.ts
- src/VSCodeUI.ts
- src/extension.ts
- src/mavenOutputChannel.ts
- src/mavenTerminal.ts
Nothing new, just better organization.
> Refactor: UI Utils.

- src/completionProvider.ts
- src/extension.ts
1. Add the provider, and put in `context.subscriptions`.
2. Fix: Also put other disposables into `context.subscriptions`.
> Add completion item provider.

- src/completionProvider.ts
> Decrease memory usage for local maven repo indices.

- package.json
- package.nls.json
- package.nls.zh.json
- src/extension.ts
part of #195 
By default, turn the feature off.
> Add a feature flag for the completion.

- src/completionProvider.ts
1. Support version completion. 
2. Fix NPE.
> Add completion for version node.

- src/completionProvider.ts
- src/extension.ts
This PR will fix #203 and #204
> Specify TextEdit for completion items.

- src/explorer/model/WorkspaceFolder.ts
See #210 
```ts
const allProjectNodes: MavenProject[] = mavenExplorerProvider.mavenProjectNodes;
```
Above statement gets all projects in the workspace (including the ones which don't belong to current root folder)
> Fix project view for multiroot workspaces.

- package.nls.json
- src/completionProvider.ts
- src/extension.ts
1. Always provide code snippets.
2. Complete for groupId/artifactId/version for all occurrences.
> Provide completion in more cases. 

- src/utils/Utils.ts
> Prevent background tasks from grabing focus

- src/utils/Utils.ts
> Fix regression: wrong command name for custom goals

- src/archetype/ArchetypeModule.ts
The command `Generate from Maven Archetype` can be triggered from:
- a) Command palette.
- b) Context menu of a folder. 
For a), a default location is missing, this PR use the first workspace folder (if there is) as the default target folder.
> Use workspaceFolder as the default target folder when creating projects

- src/completion/centralProvider.ts
- src/completion/completionProvider.ts
- src/completion/lexerUtils.ts
- src/completion/requestUtils.ts
> Refine utils for future reuse

- package.json
- package.nls.json
- package.nls.zh.json
- src/completion/lexerUtils.ts
- src/completion/requestUtils.ts
- src/extension.ts
- src/handlers/addDependencyHandler.ts
> add shortcut command to add dependency in current pom.xml

- package-lock.json
- package.json
- src/Settings.ts
- src/completion/completionProvider.ts
- src/explorer/mavenExplorerProvider.ts
- src/explorer/model/MavenProject.ts
- src/explorer/model/WorkspaceFolder.ts
- src/extension.ts
- src/handlers/addDependencyHandler.ts
- src/hover/hoverProvider.ts
- src/taskExecutor.ts
- src/utils/Utils.ts
- src/utils/historyUtils.ts
- src/utils/lexerUtils.ts
- src/utils/mavenUtils.ts
- src/utils/requestUtils.ts
- src/utils/uiUtils.ts
- src/xml-zero-lexer.d.ts
- tslint.json
As I installed the latest vscode-tslint extension, it warned me lots of issues.
> Fix tslint issues

- package.json
add simple validation in case users are not aware of the properties.
> Add simple validation

- package-lock.json
- package.json
- package.nls.json
- package.nls.zh.json
- src/Settings.ts
- src/extension.ts
- src/handlers/debugHandler.ts
- src/mavenTerminal.ts
- src/utils/mavenUtils.ts
1. create a terminal with debugging jvm args injected by MAVEN_OPTS
2. execute mvn goal
3. attach debugger
> Enable debugging plugin goal

- src/handlers/debugHandler.ts
> Check java debugger enabled status before debugging

- package-lock.json
- src/Settings.ts
- src/archetype/Archetype.ts
- src/archetype/ArchetypeModule.ts
- src/completion/completionProvider.ts
- src/explorer/mavenExplorerProvider.ts
- src/explorer/model/EffectivePom.ts
- src/explorer/model/ITreeItem.ts
- src/explorer/model/MavenPlugin.ts
- src/explorer/model/MavenProject.ts
- src/explorer/model/Menu.ts
- src/explorer/model/ModulesMenu.ts
- src/explorer/model/WorkspaceFolder.ts
- src/explorer/pluginInfoProvider.ts
- src/extension.ts
- src/handlers/addDependencyHandler.ts
- src/handlers/debugHandler.ts
- src/handlers/runFavoriteCommandsHandler.ts
- src/handlers/showDependenciesHandler.ts
- src/hover/hoverProvider.ts
- src/mavenTerminal.ts
- src/taskExecutor.ts
- src/utils/Utils.ts
- src/utils/contextUtils.ts
- src/utils/historyUtils.ts
- src/utils/lexerUtils.ts
- src/utils/mavenUtils.ts
- src/utils/requestUtils.ts
- src/utils/uiUtils.ts
- tsconfig.json
> Add TS strict null check

- package-lock.json
- package.json
this command requires a maven project as param.
> hide showDependency from command palette

- src/utils/historyUtils.ts
Assigned wrong value in TS NULL check refactoring.
> Fix regression #294

- README.md
> Add Customize Favorite Maven Commands section to README

- CHANGELOG.md
- src/utils/mavenUtils.ts
> wrap pom path with quotes to handle whitespaces

- package-lock.json
- package.json
- src/utils/lexerUtils.ts
Related issue: #310 #311 
When adding TS null check, the condition was wrongly changed in PR #288
> Fix pom auto-completion

- package.json
- package.nls.json
- src/Settings.ts
- src/extension.ts
- src/utils/Utils.ts
> Add pomfile.globPattern configuration setting

- src/explorer/model/MavenProject.ts
> Check if sub-project path is file

- CHANGELOG.md
- src/archetype/ArchetypeModule.ts
- src/completion/completionProvider.ts
- src/completion/localProvider.ts
- src/utils/contextUtils.ts
close https://github.com/microsoft/vscode-maven/issues/322
> use Maven local repository from settings

- src/completion/localProvider.ts
It's a patch for #327 
LocalProvider.localRepository was initialized before localRepository was read.
> fix completion when localRepository has not been loaded

- src/explorer/model/MavenProject.ts
> fix regression for non-exist module

- TestPlan.md
1. Some features have changed behavior.
2. Add some new feature tests.
> Update Test plan

- package-lock.json
- package.json
- src/utils/mavenUtils.ts
> use embedded mvnw only when mvn is not found in PATH

- package-lock.json
- src/explorer/model/MavenProject.ts
see [no-unsafe-finally](https://eslint.org/docs/rules/no-unsafe-finally)
> fix tslint

- package-lock.json
- package.json
Follow VS Code's official guide to migrate to `@types/vscode`
> use @types/vscode

- package.json
> Fix homepage link

- src/explorer/pluginInfoProvider.ts
See https://github.com/microsoft/vscode-maven/issues/340#issuecomment-511125457
> Remove ANSI escape code from command output

- src/archetype/ArchetypeModule.ts
swallow `OperationCanceledError`
> stop sending errors when user cancels an operation

- package-lock.json
- package.json
- src/mavenTerminal.ts
> Get default terminal via vscode.env.shell

- src/utils/historyUtils.ts
> Remove meaningless console.error

- README.md
> List settings in README

- CHANGELOG.md
- package-lock.json
- package.json
> Bump version to 0.18.2

- .vscode/settings.json
- javaConfig.json
- jdtls.ext/.gitignore
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/build.properties
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/com.microsoft.java.maven.plugin/src/main/java/com/microsoft/java/maven/handler/DelegateCommandHandler.java
- package-lock.json
> Fix m2 library for OSGi

- .travis.yml
- .vscodeignore
- gulpfile.js
- package.json
> Refactor: optimize build script

- jdtls.ext/.gitignore
- jdtls.ext/.project
- jdtls.ext/com.microsoft.java.maven.plugin/.classpath
- jdtls.ext/com.microsoft.java.maven.plugin/.project
Workaround for https://github.com/testforstephen/vscode-pde/issues/9
> add PDE project config

- package.json
Remove the update command in package.json
> Remove update command

- CHANGELOG.md
- package-lock.json
- package.json
> Bump version to 0.19.0

- .vscode/settings.json
- CHANGELOG.md
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/com.microsoft.java.maven.plugin/src/main/java/com/microsoft/java/maven/AddDependencyHandler.java
- jdtls.ext/com.microsoft.java.maven.plugin/src/main/java/com/microsoft/java/maven/ArtifactSearcher.java
- jdtls.ext/com.microsoft.java.maven.plugin/src/main/java/com/microsoft/java/maven/NetResponseResult.java
- jdtls.ext/com.microsoft.java.maven.plugin/src/main/java/com/microsoft/java/maven/handler/DelegateCommandHandler.java
- jdtls.ext/pom.xml
- package-lock.json
- package.json
> Bump version to 0.19.1

- resources/maven-wrapper/.mvn/wrapper/maven-wrapper.properties
A known issue of 3.6.1 is metioned in #415
> Upgrade embedded mvnw to 3.6.2

- src/handlers/addDependencyHandler.ts
> allow to select a project when adding a dependency

- package.json
- resources/icons/dark/list-flat.svg
- resources/icons/dark/list-tree.svg
- resources/icons/dark/view-flat.svg
- resources/icons/dark/view-hierarchical.svg
- resources/icons/light/list-flat.svg
- resources/icons/light/list-tree.svg
- resources/icons/light/view-flat.svg
- resources/icons/light/view-hierarchical.svg
> update tree/flat view icons

- src/artifactSearcher.ts
> enable lazy activation of JLS

- Troubleshooting.md
Changed "backround" to "background"
> Quick typo fix

- CHANGELOG.md
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package-lock.json
- package.json
> Upversion to 0.20.1

- src/artifactSearcher.ts
Now it's consistent to show the entry in Hovering and Code Actions. Following below rules.
```java
variable.foo();   // no show, because initial letter is in lower case
ClassName.foo();  // show, because initial letter is in upper case
AClass a;  // show
aClass a;  // show
```
> Better timing to offer resolving unknown types

- CHANGELOG.md
- jdtls.ext/pom.xml
- package-lock.json
- package.json
- src/handlers/runFavoriteCommandsHandler.ts
> Upversion to 0.20.2

- src/mavenTerminal.ts
See #452 , and this requires a full regression test...
> remove unnecessary prefix for powershell command

- src/explorer/mavenExplorerProvider.ts
- src/extension.ts
- src/utils/Utils.ts
> reload projects metadata on changing workspace folder

- src/handlers/addDependencyHandler.ts
This PR enables other extensions(e.g. dependency viewer) to trigger the command, with the pom.xml provided.
> allow to specify pomfile in command maven.project.addDependency

- src/utils/uiUtils.ts
> shortcut to view output when error occurs

- src/Settings.ts
- src/utils/mavenUtils.ts
> allow to browse for local maven binary if not found

- src/mavenTerminal.ts
- src/utils/mavenUtils.ts
> Open terminal correct workspace root folder

- CHANGELOG.md
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package-lock.json
- package.json
> Upversion to 0.21.1

- resources/maven-wrapper/.mvn/wrapper/maven-wrapper.properties
- src/archetype/ArchetypeModule.ts
> use maven-archetype-plugin:3.1.2

- package.json
- src/Settings.ts
- src/handlers/debugHandler.ts
- src/mavenTerminal.ts
- src/utils/mavenUtils.ts
> Fix #487: can set folder level custom envs

- src/utils/contextUtils.ts
- src/utils/mavenUtils.ts
Part of action items in https://github.com/microsoft/vscode-maven/issues/319#issuecomment-601494862
> keep the cache file there after calculating effective pom

- webpack.config.js
> fix webpack warning

- src/utils/mavenUtils.ts
> .mvn folder is not a must

- src/mavenTerminal.ts
- src/utils/mavenUtils.ts
See https://github.com/microsoft/vscode-maven/pull/494#issuecomment-633869294
> always append .cmd for mvn executable on Windows

- CHANGELOG.md
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package-lock.json
- package.json
> upversion to 0.22.0

- package.nls.json
- package.nls.zh.json
See https://github.com/microsoft/vscode-java-dependency/pull/274#issuecomment-654601361
> rename maven project explorer

- src/handlers/addDependencyHandler.ts
- src/handlers/runFavoriteCommandsHandler.ts
- src/utils/Utils.ts
- src/utils/uiUtils.ts
> Skip selection of project when there is only one

- CHANGELOG.md
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package-lock.json
- package.json
- src/artifactSearcher.ts
> upversion to 0.23.0

- src/extension.ts
- src/utils/contextUtils.ts
- src/utils/mavenUtils.ts
> require trust for maven wrapper per workspace

- CHANGELOG.md
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package-lock.json
- package.json
> upversion to 0.24.1

- package.json
- src/extension.ts
requires https://github.com/microsoft/vscode-java-dependency/pull/311
> add 'open pom' command to Project Manager

- .gitignore
- CHANGELOG.md
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package-lock.json
- package.json
> upversion to 0.24.2

- package.json
Move “Open POM file"  into context menu, see below
> move 'open pom' button to context menu

- CHANGELOG.md
- jdtls.ext/.project
- jdtls.ext/com.microsoft.java.maven.plugin/.project
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package-lock.json
- package.json
> upversion to 0.25.0

- src/utils/contextUtils.ts
- src/utils/historyUtils.ts
> use independent temp folder per user

- src/archetype/loadArchetypesStep.ts
- src/archetype/selectVersionStep.ts
> Fix: Rollback field have a semicolon ";"

- package-lock.json
- package.json
- src/extension.ts
- src/utils/cpUtils.ts
- src/utils/mavenUtils.ts
> Hide Maven explorer for non-Maven workspaces

- tsconfig.json
Enable `noImplicitAny` and `alwaysStrict` in tsconfig.
> update tsconfig settings

- package.json
Signed-off-by: Sheng Chen <sheche@microsoft.com>
> Hide create maven archetype command in palette if dependency viewer enabled

- src/completion/indexProvider.ts
- src/extension.ts
- src/jdtls/artifactSearcher.ts
- src/utils/uiUtils.ts
- move `artifactSearcher` into folder `jdtls`
- extract `registerCommand` to `uiUtils`
> refactor utilities

- src/definition/definitionProvider.ts
- src/explorer/model/MavenProject.ts
- src/extension.ts
- src/hover/hoverProvider.ts
> can navigate to dependency pom

- CHANGELOG.md
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package-lock.json
- package.json
> upversion to 0.27.0

- package.json
> refine contextual title

- package-lock.json
- src/extension.ts
fix https://github.com/microsoft/vscode-maven/issues/558#issue-751914502
> can nagivate dependency from .pom files

- src/definition/definitionProvider.ts
As suggested in https://github.com/microsoft/vscode/issues/113946#issuecomment-755970711, using `LocationLink` instead of `Location`.
> fix original selection range of definition

- package-lock.json
- package.json
- src/experimentationService.ts
- src/extension.ts
Signed-off-by: Sheng Chen <sheche@microsoft.com>
> Adopt TAS client

- README.md
- package-lock.json
- package.json
- src/archetype/ArchetypeModule.ts
- src/completion/localProvider.ts
- src/definition/definitionProvider.ts
- src/explorer/model/MavenProject.ts
- src/extension.ts
- src/utils/cpUtils.ts
- src/utils/editUtils.ts
Misc. changes, including:
* fix vulnerabilities
* update readme for new settings
* strict null check
* replace then/catch with async/await promises
> eng: fix null check and handle promises gracefully

- src/definition/definitionProvider.ts
to fix regression introduced by https://github.com/microsoft/vscode-maven/commit/6d0dce9601c6b615bfcbbe26140681e0b4dffb42#diff-172425749fb7be01b45f53e738a47e08320b708cca50a039eac023905c908eaaR35
> fix regression of definition provide

- src/archetype/Archetype.ts
- src/completion/completionProvider.ts
- src/completion/indexProvider.ts
- src/explorer/model/MavenPlugin.ts
- src/jdtls/commands.ts
> fix POM completion when LS in lightweight mode

- package.json
- src/explorer/model/LifecycleItem.ts
- src/explorer/model/LifecycleMenu.ts
- src/explorer/model/LifecyclePhase.ts
- src/explorer/model/MavenProject.ts
- src/extension.ts
- src/utils/Utils.ts
- tslint.json
the icon "sync" means lifecycle
the icon "gear" is same with IntelliJ IDEA, optimized for developers coming from there.
> add lifecycle into maven explorer

- src/explorer/model/MavenProject.ts
> parse properties in project name

- package-lock.json
- package.json
- src/experimentationService.ts
- src/extension.ts
Signed-off-by: Sheng Chen <sheche@microsoft.com>
> Adopt new APIs from vscode-tas-client

- src/explorer/model/MavenProject.ts
Potential NPE. See screenshot in #611 (unrelevant with the issue itself)
> Fix: Cannot read property 'ePom' of undefined

- CHANGELOG.md
- package-lock.json
- package.json
> upversion to 0.30.0

- CHANGELOG.md
- package-lock.json
- package.json
- src/archetype/ArchetypeModule.ts
> upversion to 0.30.1

- src/codeAction/codeActionProvider.ts
- src/extension.ts
> add code action: add a dependency

- CHANGELOG.md
- package-lock.json
- package.json
> upversion to 0.31.0

- .gitignore
- package-lock.json
- package.json
- src/utils/editUtils.ts
API changed in languageclient@7
> upgrade language client lib

- src/DiagnosticProvider.ts
- src/codeAction/conflictResolver.ts
- src/explorer/model/DependenciesMenu.ts
- src/explorer/model/iDiagnostic.ts
- src/extension.ts
- src/handlers/parseRawDependencyDataHandler.ts
- src/handlers/setDependencyVersionHandler.ts
This PR provides diagnostics and codeActions in pom file for conflict dependencies. 
part of #261
https://user-images.githubusercontent.com/25446374/126902565-7d2c4fde-b831-4c59-983e-6a8e4b89c309.mp4
> add diagnostics and related codeActions for conflict dependencies

- CHANGELOG.md
- package-lock.json
- package.json
> upversion to 0.32.0

- src/explorer/decorationProvider.ts
- src/explorer/model/OmittedStatus.ts
- src/handlers/parseRawDependencyDataHandler.ts
fix #676  , also adding badge and tooltip.
See screenshots in https://github.com/microsoft/vscode-maven/issues/676#issuecomment-887337100
> de-emphasize duplicate dependencies

- src/handlers/parseRawDependencyDataHandler.ts
> fix: delete extra space in scope

- src/handlers/showDependenciesHandler.ts
> move notification of deps calculation to status bar

- CHANGELOG.md
- package-lock.json
- package.json
- src/utils/mavenUtils.ts
> 0.32.1: stop creating temp files in workspace

- src/handlers/addDependencyHandler.ts
> fix: insert malformed depenedency when pom.xml is dirty

- src/DiagnosticProvider.ts
- src/explorer/model/Dependency.ts
- src/explorer/model/OmittedStatus.ts
- src/handlers/excludeDependencyHandler.ts
- src/handlers/parseRawDependencyDataHandler.ts
- src/handlers/setDependencyVersionHandler.ts
> refine omittedStatus

- CHANGELOG.md
- package-lock.json
- package.json
> upversion to 0.32.2

- src/handlers/jumpToDefinitionHandler.ts
> fix: .pom file not highlighted

- package.json
see https://github.com/microsoft/vscode-maven/issues/701#issuecomment-897478010
> Lifecycle phase item: add run entry in context menu

- package-lock.json
- package.json
- src/DiagnosticProvider.ts
- src/debouncing.ts
- src/explorer/model/DependenciesMenu.ts
- src/explorer/model/MavenProject.ts
- src/handlers/parseRawDependencyDataHandler.ts
fix #692, refresh diagnostics if the pom file has changed.
Also apply adaptive debounce to improve the performance.
> fix: diagnostics do not refresh after editing pom file

- .azure-pipelines/ci.yml
After it's checked in, I'll create a pipeline binding to this file.
> init yaml-based azure pipelines

- package.json
- src/explorer/model/DependenciesMenu.ts
- src/explorer/model/HintNode.ts
- src/explorer/model/LifecyclePhase.ts
- src/explorer/model/MavenPlugin.ts
- src/explorer/model/MavenProject.ts
- src/explorer/model/Menu.ts
- src/explorer/model/PluginGoal.ts
- src/explorer/model/WorkspaceFolder.ts
> unify context value scheme of tree items

- package.json
- package.nls.json
- package.nls.zh.json
- src/extension.ts
> add setting for project opening method

- CHANGELOG.md
- package-lock.json
- package.json
> upversion to 0.33.0

- src/explorer/model/DependenciesMenu.ts
add `refresh()` for DependenciesMenu to save dirty pom file.
> add refresh to DependenciesMenu

- .vscodeignore
- package-lock.json
> eng: fix vulnerability & exclude scripts from .vsix package

- package-lock.json
- package.json
> remove unused dependency

- src/contentProvider.ts
- src/definition/definitionProvider.ts
> open .pom file in RO mode

- package-lock.json
- package.json
- src/archetype/createProject/SelectArchetypeStep.ts
- src/codeAction/conflictResolver.ts
- src/completion/centralProvider.ts
- src/completion/indexProvider.ts
- src/completion/localProvider.ts
- src/explorer/model/Dependency.ts
- src/explorer/model/MavenProject.ts
- src/extension.ts
- src/handlers/addDependencyHandler.ts
- src/handlers/excludeDependencyHandler.ts
- src/handlers/goToEffectiveHandler.ts
- src/handlers/parseRawDependencyDataHandler.ts
- src/handlers/setDependencyVersionHandler.ts
- src/handlers/showDependenciesHandler.ts
- src/jdtls/artifactSearcher.ts
- src/utils/Utils.ts
- src/utils/historyUtils.ts
- tslint.json
use same TSlint rules with other Java extensions. 
meanwhile resolve vulnerabilities by removing unnecessary dependencies.
> chore: change TSLint rules

- .vscode/tasks.json
- package.json
> chore: update watch tasks

- CHANGELOG.md
- package-lock.json
- package.json
> upversion to 0.34.0

- CHANGELOG.md
- package-lock.json
- package.json
> up version to 0.34.2

- src/archetype/ArchetypeModule.ts
> apply maven.executable.options on creating projects

- src/handlers/debugHandler.ts
> attach debug session after port is being listened

- src/archetype/ArchetypeModule.ts
- src/archetype/createProject/SelectArchetypeStep.ts
- src/archetype/createProject/SpecifyArchetypeVersionStep.ts
- src/archetype/createProject/SpecifyArtifactIdStep.ts
- src/archetype/createProject/SpecifyGroupIdStep.ts
- src/archetype/createProject/SpecifyTargetFolderStep.ts
- src/archetype/createProject/index.ts
- src/archetype/createProject/types.ts
Regression in PR #775 : cannot go back to previous step. 
Now at the beginning, we decide the steps based on args provided.
> continue PR #775

- CHANGELOG.md
- package-lock.json
- package.json
> upversion to 0.35.0

- src/completion/completionProvider.ts
close #787 
Same issue occur not only for version, but also group Id and artifact Id.
> fix completion range

- src/explorer/model/LifecycleMenu.ts
> add test-compile into common lifecycles

- src/explorer/model/MavenProject.ts
> add tooltip showing pom path

- CHANGELOG.md
- package-lock.json
- package.json
> up version to 0.35.1

- package.json
- src/completion/constants.ts
- src/explorer/model/LifecycleMenu.ts
- src/extension.ts
- src/utils/Utils.ts
> register commands for test-compile

- CHANGELOG.md
- package-lock.json
- package.json
> up version to 0.35.2

- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/pom.xml
Follow upstream jdtls to require JDK 17.
> require JDK 17 to build plugin

- CHANGELOG.md
- package-lock.json
- package.json
> up version to 0.36.0

- package-lock.json
- package.json
> update telemetry wrapper for @vscode/extension-telemetry@0.6.2

- src/completion/completionProvider.ts
- src/utils/lexerUtils.ts
> fix completion range in pom.xml

- package.json
- package.nls.json
- package.nls.zh-cn.json
- package.nls.zh-tw.json
- src/extension.ts
> add shortcut to reload all maven projects

- src/completion/completionProvider.ts
- src/explorer/model/MavenProject.ts
- src/utils/lexerUtils.ts
> completion for properties

- CHANGELOG.md
- package-lock.json
- package.json
> up version to 0.37.0

- src/completion/providers/SchemaProvider.ts
> remove unnecessary EOL for textNode completion

- src/utils/mavenUtils.ts
See https://github.com/microsoft/vscode-maven/issues/852#issuecomment-1197970387
> update depgraph-maven-plugin to 4.0.2

- src/mavenTerminal.ts
> fix #874: git-bash wrongly recognized as wsl

- src/handlers/dependency/addDependencyHandler.ts
> can filter dependencies to add by groupId

- src/DiagnosticProvider.ts
mitigate #815
The error was thrown when calculating corresponding diagnostics for dependency conflicts. There are still cases observing this error, but we are not able to reproduce it with a proper sample project.
Here to log into console instead of throwing an error, and this unblock users from the error. Other diagnostics will still be provided if corresponding range can be found.
> should not break the feature when conflict nodes not found

- CHANGELOG.md
- package-lock.json
- package.json
> up version to 0.39.1

- src/archetype/createProject/SpecifyArtifactIdStep.ts
- src/archetype/createProject/SpecifyGroupIdStep.ts
> fix abuse of InputBox.enabled API

- package.json
- src/Settings.ts
- src/explorer/model/FavoriteCommand.ts
- src/handlers/favorites/addFavoriteHandler.ts
> simplify workflow adding favorite commands

- src/handlers/debugHandler.ts
> fix incorrect invocation when debugging plugin goal

- jdtls.ext/com.microsoft.java.maven.plugin/.classpath
- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/build.properties
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- package.json
fix #921 , updating commons-text from 1.7 to 1.10.0
> fix CVE-2022-42889

- src/utils/contextUtils.ts
fix #924 
(introduced by https://github.com/microsoft/vscode-maven/commit/db028b3dc4ced9837ea6609bc51122d8ca1316d6#diff-a2b9078fc2f74c772f756ca0ab1fc23d5fe9b2a70c65c1cb3c666c559c7e3bf9R48 )
> fix regression when customized localRepository is set in settings.xml

- jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
- jdtls.ext/com.microsoft.java.maven.plugin/build.properties
- jdtls.ext/com.microsoft.java.maven.plugin/pom.xml
- jdtls.ext/pom.xml
- jdtls.ext/target.target
- test/projects/maven/src/main/java/com/mycompany/app/App.java
> fix: bundle org.slf4j.api renamed to slf4j.api

- src/definition/definitionProvider.ts
fix the case where parent POM is from repository.
E.g.
```
<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.7.3</version>
</parent>
```
> improve navigation of parent POM

- src/archetype/ArchetypeModule.ts
> Fix the error that cannot create JavaFX projects
