CHANGELOG.md, README.md, package.json, src/VSCodeUI.ts
Currently, the maven integration only works if the JAVA_HOME environment variable is set permanently.  But setting JAVA_HOME permanently is inconvenient in many cases - especially if we are testing against many different versions of Java.
There is an existing configuration property in the VS Code Java support to configure JAVA_HOME - the "java.home" setting.
This PR adds a configuration property to the maven extension: "maven.set.javaHome".  If true, and if java.home is set, then the JAVA_HOME environment variable will be set to the configured value when a new terminal is opened.
I've tested this with Powershell, CMD, and GitBash and it works as expected.
=> Add ability to setup environment variables before calling Maven

FAQ.md, src/Utils.ts, src/extension.ts, tslint.json
=> Guide users to setup correct mvn executable path

src/Utils.ts
#67 
`mvnw` will look for its .jar files recursively under current directory. Set `cwd` to ensure it works normally.
=> for #67: fix for `mvnw --vesrion`

CHANGELOG.md, package-lock.json, package.json, src/Utils.ts, src/extension.ts
Test cases:
```    
"maven.executable.path": "./mvnw",
"maven.executable.path": "C:\\Users\\yanzh\\Desktop\\web5\\mvnw",
"maven.executable.path": "",
```
=> fix bug of using `./mvnw` as maven executable

package.json, src/extension.ts
In this PR: 
1. Activate extension if pom.xml found anywhere within the workspace (previously only under root folder)
2. Show maven projects explorer only when extension is activated. This solves issues: #36 #51
=> Show Maven Projects Explorer only when extension is activated.

package.json, src/Utils.ts, src/archetype/ArchetypeModule.ts, src/extension.ts
Work item #84 .
1. allow to set different `maven.executable.path` for each workspace folder.  Related issue: #79 
2. check maven availability for each workspace folder if only `**/pom.xml` is found in it.
=> force to use mvn wrapper if found in workspace root folder

src/VSCodeUI.ts, src/extension.ts
Now we don't run mvn --version at startup. 
Pop up troubleshooting guide for all errors.
TODO: add hint to find detailed error messages (e.g. outputChannel) in troubleshooting page.
=> avoid noise: only show troubleshooting guidance when error occurs

package-lock.json, src/Settings.ts, src/Utils.ts
To fix warining message
Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for 'maven.executable.path', provide the URI of a resource or 'null' for any resource.
=> fix warning: explicitly specify null for resource scope conf

src/Utils.ts, src/explorer/model/MavenProjectNode.ts, src/explorer/model/WorkspaceFolderNode.ts
- Fixed a TS typing error on a boolean variable.
- Updated `_ensureMavenProjectParsed` of `MavenProjectNode` to become public.
- Alphabetically sort the array of `MavenProjectNode` items in `WorkspaceFolderNode`.
If I've made any mistakes or if there is a better way of approaching the problem, please let me know.
=> Sort maven project list in Explorer and hide invalid pom.xml files

package.json
This explorer never shows before extension activation. So you can never activate the extension "onView" the explorer. 🤣 
```jsonc
"views": {
"explorer": [
{
"id": "mavenProjects",
"name": "Maven Projects",
"when": "mavenExtensionActivated"
}
]
},
```
=> Remove unused activation event.

package-lock.json, package.json
Update the patch version. In `0.3.1` **OperationalError** is renamed to **OperationError**. Here in this repo we are not using it, so not code changes except the version.
=> Update version of telemetry wrapper.

package-lock.json, package.json, src/extension.ts
This PR:
* upgrades version of vscode-extension-telemetry-wrapper to v0.3.3 (which uses the latest vscode-extension-telemetry@0.0.22). See issue #135  .
* disposes the reporter (to send out all queued events) when the extension is deactivated.
=> Upgrade telemetry wrapper

src/Utils.ts
* Changed `currentWindowsShell` to be more generic and straighforward
* Changed `toWSLPath` to return path converting `\` to `/` even when
not containing a `:\\`
closes #142
=> Better support for WSL

package-lock.json, package.json
To resolve the alert. 
```
Vulnerable versions: > 3.3.4
Patched version: No fix
The NPM package flatmap-stream is considered malicious. A malicious actor added this package as a dependency to the NPM event-stream package in versions 3.3.6 and later. Users of event-stream are encouraged to downgrade to the last non-malicious version, 3.3.4.
Users of flatmap-stream are encouraged to remove the dependency entirely.
```
=> Use vscode@1.1.22 to fix vulnerability issue of event-stream.

src/explorer/PluginInfoProvider.ts, src/explorer/model/MavenPlugin.ts, src/explorer/pluginInfoProvider.ts, src/extension.ts
Use a `PluginInfoProvider` to get detailed info of a maven plugin, e.g. prefix, goals.
It uses the `ExtensionContext.globalState` as the cache to improve perf.
=> Use globalState to cache plugin info.

src/explorer/model/MavenProject.ts
See: #182 
In this PR, when adding/modifying a pom.xml in current workspace, `refresh` is triggered:
* if the project is collapsed: only parse the pom and update the label with latest artifact id. 
* if the project is expanded: it calls `getChildren` automatically, where effective pom is calculated if missing.
=> Do not calculated effective-pom on refreshing a collapsed project.

package.json, src/extension.ts
Previously to avoid noise, we only show the explorer if a pom.xml file is found in the workspace.
For new users, if no workspace folder is open, it's hard to find the explorer after installation.
=> Add onView activation event

package-lock.json, package.json, src/completionProvider.ts, src/xml-zero-lexer.d.ts
See #195 
1. Use `xml-zero-lexer`  to tokenize pom.xml
2. Provider completion results only when cursor is in node `dependency>groupId` or `dependency>artifactId`
=> Provide completion items only for dependency nodes.

package.json, package.nls.json, package.nls.zh.json, resources/dark/view-flat.svg, resources/dark/view-hierarchical.svg, resources/light/view-flat.svg, resources/light/view-hierarchical.svg, src/Settings.ts, src/explorer/mavenExplorerProvider.ts, src/explorer/model/MavenProject.ts, src/explorer/model/WorkspaceFolder.ts, src/extension.ts
For #193 .
1. use a config to control view type. 
2. add commands to switch between the views.
In this PR, I didn't recover the "Modules" node, the modules are listed directly under the parent project, below the "Plugin" node. I think It's more concise.
=> Allow to switch flat/hierarchical view of projects & modules

package.json, package.nls.json, package.nls.zh.json, src/completion/centralProvider.ts, src/completion/localProvider.ts, src/extension.ts, src/utils/Utils.ts
Original issue: #195 , Continuing work of #197 
- Remove indexing work which cause huge time and CPU cost.
- Searching local Maven repository on completion, with depth of 2. (good performance)
- Typo fixing
- Stop using hard-coded m2_home
- Sort versions in reverse order.
=> Retrieve completion items from local Maven repository on the fly

package-lock.json, package.json, src/completion/centralProvider.ts, src/completion/localProvider.ts, src/completion/versionUtils.ts
Original issue: #195 
Versions are sorted with the latest at the top, in the following way via the util `getSortText(ver)`:
- Format of a semantic version is `major`.`minor`.`patch`-`identifier`
- Given a max value of 999 (in most cases) `sortText` is a string joined by `999-major`, `999-minor`, `999-patch`, with leading zeros.
- A non-semantic version is regarded as "0.0.0" when being sorted.
`9.0.0` will be sorted by text "990999999"
`1.2.3-SNAPSHOT` will be sorted by text "998997996"
`4.5` will be sorted by text "999999999"
=> Sort version completion items

package.json
The scope should be "window", should be shared among workspaceFolders.
When a user hits the button from explorer to switch the view, it's unable to identify the resource.
=> Fix scope of the config maven.view

package-lock.json, src/completion/centralProvider.ts, src/completion/requestUtils.ts
For #195 
In VSCode Insider, http.proxy_support = override by default, and the request breaks in some cases.
=> Robustness: safer request url

src/completion/IArtifactProvider.ts, src/completion/centralProvider.ts, src/completion/completionProvider.ts, src/completion/localProvider.ts, src/extension.ts
Previously it uses two completion providers, with duplicated results sometimes.
Now combine them into one, removing the dup items.
=> Remove duplicated items in completion list

src/completion/centralProvider.ts, src/completion/completionProvider.ts, src/completion/lexerUtils.ts, src/completion/localProvider.ts
This PR adds additionalTextEdit for artifact ID completion items to achieve the goal.
1. Changed `ElementNode` as we need to know both start/end position of groupId node. 
2. Information of group Id is carried in CompletionItem.data (standard LSP, but not defined in vscode.d.ts)
=> Update groupId together if possible when completing artifactId

src/completion/completionProvider.ts
A pitfall of using `(0.0.0,)` or `LATEST`: chaos in dependency management. The author can hardly know the resolved version. That's why `LATEST` is deprecated. 
This PR removes the default value, letting users specify it by themselves.
=> Remove default version in snippets

package.json
For #232 .
In this PR, the extension will be activated if any *.xml file is open. As the completion provider is registered only for pattern `**/pom.xml`, it won't bring any overload for non-pom XML files.
=> Activate extension on opening external pom.xml

src/completion/centralProvider.ts, src/completion/completionProvider.ts, src/completion/constants.ts, src/completion/localProvider.ts, src/extension.ts
- It calls command `maven.completion.selected` whenever an item is selected.
- It sends `{completeFor: string, source: string}` as the info. 
- completeFor: dependency/plugin/groupId/artifactId/version
- source: snippet/maven-local/maven-central
=> send telemetry when completion item selected

package-lock.json, package.json, src/completion/versionUtils.ts
As versions of artifacts from Spring Boot Framework don't strictly follow the semantic version, this PR is supposed to fix #236 by loosely parse the version.
=> sort for non-strict semantic versions

package.json, src/utils/uiUtils.ts
=> Use openExternal to open troubleshooting page.

package.json, src/utils/uiUtils.ts
Reverts Microsoft/vscode-maven#248
As it doesn't bring any change to the user experience. Revert it to unblock lower version from the coming new features.
=> Revert "Use openExternal to open troubleshooting page."

src/Settings.ts, src/archetype/ArchetypeModule.ts, src/explorer/model/EffectivePom.ts, src/explorer/model/MavenProject.ts, src/extension.ts, src/hover/hoverProvider.ts, src/mavenTerminal.ts, src/utils/Utils.ts, src/utils/contextUtils.ts, src/utils/cpUtils.ts, src/utils/historyUtils.ts, src/utils/mavenUtils.ts
Break down `Utils` into:
- contextUtils: Context related utils, path calculation, etc. 
- cpUtils: execute external process
- historyUtils: maven goal history related, LRU cache
- mavenUtils: execute background maven command to get string output, e.g. effective pom, plugin description
Extract EffectivePom as a class.
=> Refactor: break down utils.

package.json
Previously this command is shown in command palette. But without any parameter, it cannot be successfully executed.
=> Hide maven.plugin.execute from command palette

src/explorer/model/EffectivePom.ts, src/explorer/model/MavenProject.ts
#260 
Hover info (effective version) requires effective pom, so we trigger it for users on startup. It's using the taskExecutor, one task at most in the same time, to avoid high CPU cost.
=> Calculate effective pom in background on startup

CHANGELOG.md, TestPlan.md, package.json, package.nls.json, src/Settings.ts, src/extension.ts, src/handlers/runFavoriteCommandsHandler.ts, src/utils/Utils.ts
=> Allow to specify/execute favorite Maven commands.

TestPlan.md, package.nls.json, src/utils/Utils.ts
`Custom goals ...`  to `Custom ...`
It's now consistent with "History ..." and "Favorites ..."
=> Change wording of custom goals for consistency

src/utils/Utils.ts, src/utils/contextUtils.ts
If no workspace is open, the temp file path is not valid.
=> Fix NPE when no workspace open

package.json, package.nls.json, src/extension.ts, src/handlers/showDependenciesHandler.ts, src/utils/mavenUtils.ts
1. Run mvn dependency:tree in background to get raw tree.
2. Replace exec with spawn to get rid of max buffer issue.
=> Add shortcut to show raw dependency tree

src/mavenTerminal.ts
Somehow envs are not passed to WSL on creation, which blocks the debugging feature for WSL users.
Here's a workaround to manually "export" envs.
=> workaround for custom envs setting in WSL

src/utils/mavenUtils.ts
Previously, the string `Settings.Executable.options(vscode.Uri.file(pomfile))` will be wrongly split
=> Fix appended default args

src/utils/Utils.ts
=> Fix null check

TestPlan.md
The setting config example is wrong. I came across this example when I was trying to set up my maven favorite commands. I got errors until I realize the correct setting field should be "maven.terminal.favorite**s**"
=> Fix a typo in TestPlan

CHANGELOG.md, src/explorer/model/EffectivePom.ts, src/explorer/model/MavenProject.ts
For some reason it's possible to fail to calculate the effective pom. Previously if user expand the "Plugins" node, it requires to calculate the effective pom (but fail), and `mavenExplorerProvider.refresh(this);` always re-triggers the calculation. 
Related issue #296
=> Fix potential infinite execution loop of calculating effective-pom

src/utils/mavenUtils.ts
Refer to #304 , if mvnw is also located in path with spaces in it, it's a potential error, as child_process is not able to spawn the process.
=> fix whitespace issue in mvnw path

CHANGELOG.md, src/completion/completionProvider.ts, src/extension.ts
See: #310 
This PR improves experience of inserting code snippets by 
- adding "<" as trigger char.
- removing unexpected brackets.
=> Fix unexpected insertion of code snippets

CHANGELOG.md, src/mavenTerminal.ts
See #324 
This PR serves as a workaround to escape `[` and `]` in Powershell. 
It works for me. 
```powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.
Try the new cross-platform PowerShell https://aka.ms/pscore6
PS C:\WINDOWS\System32\WindowsPowerShell\v1.0> cd "c:\Users\yanzh\Desktop\play\``[demo``]\demo-maven"
PS C:\Users\yanzh\Desktop\play\[demo]\demo-maven> cmd /c mvn archetype:generate -DarchetypeArtifactId="azure-maven-archetypes" -DarchetypeGroupId="com.microsoft.azure"
[INFO] Scanning for projects...
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/3.1.0/maven-war-plugin-3.1.0.pom
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-war-plugin/3.1.0/m …
```
=> Escape square brackets in path in PowerShell

src/Settings.ts, src/completion/completionProvider.ts, src/extension.ts
Related issue: #310 
Snippet "<plugin> ..... </plugin>" should be trimmed if "<" or ">" already exists before the snippet applies. 
Following cases are covered now:  "|" indicates the cursor position
* <|
* <p|
* <|>
* <p|>
=> remove redundant brackets for snippets

package.json, package.nls.json, package.nls.zh.json, src/Settings.ts, src/explorer/model/EffectivePom.ts, src/explorer/model/MavenProject.ts, src/explorer/model/PluginsMenu.ts, src/extension.ts
See: #319 
To avoid performance deterioration, add a settings entry `maven.pomfile.autoUpdateEffectivePOM` which allows users to decide whether to auto-calculate effective-pom when pom.xml changes are detected.
Note: `Effective.upToDate` now serves as a flag indicating current cached effective is dirty or not.
=> Allow to specify whether to auto-update EffectivePOM

src/mavenTerminal.ts
This PR serves as a workaround for #337 , before VSCode exposes API for the default shell.
Code is based on https://github.com/microsoft/vscode-python/pull/5886
=> workaround for #337: guess default terminal

src/archetype/ArchetypeModule.ts, src/extension.ts, src/handlers/debugHandler.ts, src/handlers/runFavoriteCommandsHandler.ts, src/utils/Utils.ts, src/utils/mavenUtils.ts
- refactor util `executeInTerminal`
- use embedded mvnw only when create project. 
This fixes #352
=> Use embedded mvnw as fallback only when creating project

src/handlers/showDependenciesHandler.ts
Previously, errors are thrown directly from `rawDependencyTree(pomPath)`, without being set as user error.
=> set user error for maven.project.showDependencies

src/artifactSearcher.ts
The constant field is from: https://help.eclipse.org/2019-06/index.jsp?topic=%2Forg.eclipse.jdt.doc.isv%2Freference%2Fapi%2Fconstant-values.html
=> Use constant field to represent code value

Troubleshooting.md
In specifying the "full path" for the executable, I had it set to just `/opt/apache-maven-3.6.2/bin` as per the requirement for `$PATH`.  Adding this extra detail would have saved me some time, so might be useful in the troubleshooting section.  Thanks.
=> Add small detail for path of executable

src/explorer/mavenExplorerProvider.ts, src/explorer/model/WorkspaceFolder.ts, src/extension.ts, src/utils/Utils.ts
See #429 
* change `getAllPomPaths` to accept empty params, indicating finding pom files for all workspaceFolder.
* find all projects at startup after the extension is activated.
=> find all projects at startup

.vscode/launch.json, jdtls.ext/com.microsoft.java.maven.plugin/src/main/java/com/microsoft/java/maven/AddDependencyHandler.java, jdtls.ext/com.microsoft.java.maven.plugin/src/main/java/com/microsoft/java/maven/GetPosHandler.java, jdtls.ext/com.microsoft.java.maven.plugin/src/main/java/com/microsoft/java/maven/PosInfo.java
fix #441
During XML parsing, when `endElement`, check if the `dependencies` node is exactly under `project` node ...
=> Find correct position in POM to insert dependency

package.json, package.nls.json, package.nls.zh.json, src/handlers/debugHandler.ts, src/handlers/runFavoriteCommandsHandler.ts
This somehow resolves  #444 
It adds `debug: boolean` in schema of favorite command, and run/debug depending on the flag.
=> support to debug favorite commands

jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF
`PlexusConfiguration` is included in `org.eclipse.m2e.maven.runtime`
=> Fix ClassNotFound error

src/mavenTerminal.ts
As of today, when VSCode default's terminal is PowerShell, running a maven command opens a new cmd window, and when the process is finished, this window is closed and we can't see what happened.
With this change, we force PowerShell to run the command in it's own window.
=> Open cmd when running inside PowerShell

package-lock.json, package.json, src/types.d.ts, src/utils/mavenUtils.ts, src/xml-zero-lexer.d.ts
On Mac, the Maven Projects command adds extra double-quote around the mvn path. Example: the clean command try to execute `~/Documents/workspace/tool/apache-maven-3.6.1/bin/mvn clean`. Bash return error, No such file or directory. Change `~/Documents/workspace/tool/apache-maven-3.6.1/bin/mvn clean` to `~/Documents/workspace/tool/apache-maven-3.6.1/bin/mvn clean` and solve the problem.
=> expand tilde as home dir

src/extension.ts, src/mavenTerminal.ts
Fix error: When a Non-Maven terminal is closed, all Maven terminals are shut down.
=> Fix error: When a Non-Maven terminal is closed, all Maven terminals are shut down.

package-lock.json, package.json, src/Settings.ts, src/utils/mavenUtils.ts, tslint.json
**maven.executable.path** -> remain `machine` scope, for security concern.
**maven.executable.options** -> change to `machine-overridable`, to fix #524 
**maven.executable.preferMavenWrapper** -> revert to `resource` scope, to mitigate #523
=> refine scope of setting maven.executable.* 

package-lock.json, package.json, package.nls.json, package.nls.zh.json, src/handlers/addDependencyHandler.ts
requires https://github.com/microsoft/vscode-java-dependency/pull/311
=> register 'add dependency' command to Project Manager extension

package-lock.json, package.json, package.nls.json, package.nls.zh.json, src/extension.ts, src/utils/Utils.ts
Requires https://github.com/microsoft/vscode-java-dependency/pull/311
=> register 'execute commands' onto Project Manager

package.json, package.nls.json, src/Settings.ts
The globally enabled entry in the Explorer right-click menu is a teensy bit intrusive for users who are not working with Java/Maven exclusively or nearly so. This quick patch introduces an option to enable or disable the entry, and disables it by default.
A few notes:
- Disabling the entry by default is bound to surprise a few users at the next update. Even so, I reckon that it should be the preferred behavior.
- The informal "Generate project from maven archetypes" test from `TestPlan.md` is somewhat overloaded now that it also includes a procedure to test the menu setting. I'd be happy to split the test in two, one for the setting and one for project generation proper.
- Line endings seemed to be inconsistent across files and, within `TestPlan.md`, across lines. I have tried not to …
=> Make optional the File Explorer context menu entry

src/artifactSearcher.ts
Messages in "Hover" are in markdown format, for some reason vscode recursively decodeURIComponent, i.e. after encoding and decoding,  whitespace "%20" was first encoded as "%2520" and later decoded as  " ".
Solution, use base64 to eliminate special chars in uri. 
fix #538
=> fix for cases when special chars in uri

src/definition/definitionProvider.ts
fix https://github.com/microsoft/vscode-maven/issues/558#issuecomment-755825830
if effective pom is not correctly calculated, `<version>${azure.version}</version>` cannot be resolved, thus the target navigation link is wrong.
=> do not provide navigation link if version is unresolved

src/utils/mavenUtils.ts
> maven.terminal.customEnv: 
> Specifies an array of environment variable names and values. These environment variable values will be added to the **terminal session** before Maven is first executed.",
As described, this setting should only affect commands sent to terminal. This PR removes custom env from background commands.
=> only load custom envs in terminal commands

package-lock.json, src/utils/mavenUtils.ts
ref: #579 
cached pom is saved into workspace storage. Together there will be a file `<hash>.mtime` recording last modified time of original `pom.xml` file, indicating whether the cache is valid.
=> cache effective pom

src/explorer/EffectivePomProvider.ts, src/explorer/model/MavenProject.ts, src/utils/mavenUtils.ts
setting `prefetchEffectivePom` is false by default. So before user explicitly calculate effective pom, even though there's cache, it's not exploited. 
Now first read data from cache (if exists), as it's a fast operation.
=> load cache of epom if exists on startup

src/explorer/model/MavenPlugin.ts, src/explorer/model/MavenProject.ts
Related issue: #590 
Solution:
- Maven items
- label: show "name" if provided, "artifactId" as fallback.
- description: always show groupId : artifactId. (version is omitted as I don't think it's that important in distinguishing)
- Plugin items
- before resolving it to get detailed info (e.g. prefix), show qualified id, aka. groupId:artifactId:version
- show "prefix" if resolved, and put qualified id in description
After this PR:
=> use TreeItem.description to provide show identifier

src/completion/completionProvider.ts
See: https://github.com/microsoft/vscode-maven/issues/594
=> version completion: use default group id if not specified

src/explorer/mavenExplorerProvider.ts, src/explorer/model/MavenProject.ts
To fix #610 .
Also fixing a potential issue: properties from parent projects with custom `relativePath` were not recognized.
E.g. 
in `../parent/pom.xml`
```
<properties>
<testProp>CUSTOM_PROPERTY</testProp>
...
```
in `pom.xml`
```
<name>Spring Hadoop Samples - Hive - ${testProp}</name>
```
Now we get:
=> recognize parent.relativePath

src/archetype/ArchetypeModule.ts
if user's default shell is pwsh, args are not correctly passed/escaped
=> use CMD to create maven project on windows

src/archetype/ArchetypeModule.ts
See #623 
Now on Windows, full path of maven executable is wrapped with `"`, and full command is also wrapped:
cmd /c ""<maven-binary-path>" "<arg_0>" ... "<arg_n>""
=> fix project creation on Windows

src/utils/Utils.ts
A error message here:
Command "maven.goal.execute" fails. command 'maven.goal.Favorites ...' not found
Steps to reproduce the behavior:
1. Ctrl+Shift+P (workbench.action.showCommands)
2. Select Maven: Execute Commands
3. Select a Maven project if necessary
4. Select "Favorites ... "
5. Select a favorite command
- OS: Windows 10
- VS Code version: 1.56.0
- Extension version 0.30.1
=> Execute and return when select "Custom ..." or "Favorites ..."

package.json, package.nls.json, package.nls.zh.json, src/definition/definitionProvider.ts, src/extension.ts, src/handlers/jumpToDefinitionHandler.ts, src/utils/contextUtils.ts
this PR implements an inline command, jump to definition, for dependency node in sidebar. If click, it will open the pom file where the dependency is imported.
https://user-images.githubusercontent.com/25446374/126265383-c7a6b756-9207-4814-8eeb-b5db7929ff5e.mp4
=> implement inline command for dependency: Jump to definition

src/explorer/decorationProvider.ts, src/explorer/model/DependenciesMenu.ts, src/explorer/model/Dependency.ts, src/explorer/model/IConflictMessage.ts, src/extension.ts, src/handlers/parseRawDependencyDataHandler.ts
This pr adds a new parameter in class `Dependency` to track conflicts for both fileDecoration and diagnostics.
Also, it colors the items that have conflicts to make them more conspicuous.
part of #261
=> add conflictMessage in Dependency and implement fileDecoration

README.md, src/utils/mavenUtils.ts
Fix #637 as workspace trust has been shipped. Some users use `customEnv` to set JAVA_HOME for maven to execute. Previously it's disabled for background processes for security concern.
=> load maven.terminal.customEnv for background maven commands

src/explorer/model/Dependency.ts
Follow IDEA to omit "compile" scope for simplicity. Limited scopes like test/provided/runtime are revealed in description.
=> simplify label of dependency node

src/contentProvider.ts, src/extension.ts, src/handlers/showDependenciesHandler.ts, src/utils/Utils.ts
Previously opened as an untitled file, which has below disadvantages:
- unreadable title
- prompt for saving on closing file
Now use content provider for better UX.
=> use content provider to open epom and dependencies

src/explorer/EffectivePomProvider.ts, src/utils/mavenUtils.ts
```
if (this.effectivePom !== undefined) {
return this.effectivePom;
}
```
Once calculated, effective pom was never updated when pom.xml changed. Now removing this part, as we have FS level epom cache based on timestamp
=> fix: epom cache was never updated

src/contentProvider.ts, src/extension.ts, src/handlers/showDependenciesHandler.ts, src/utils/Utils.ts, src/utils/uiUtils.ts
vscode seems to cache the content for the same Uri. Whenever pom.xml changes, we should notify it, to update dependencies and epom.
=> notify content provider on pomxml change

src/handlers/excludeDependencyHandler.ts, src/handlers/jumpToDefinitionHandler.ts, src/handlers/setDependencyVersionHandler.ts
fix: insert malformed dependency when pom.xml is dirty for "exclude dependency", "set dependency version" and "go to definition" features.
=> fix: apply #690 to other features

src/archetype/ArchetypeModule.ts
See #689
we didn't cover the case when `vscode.workspace.workspaceFolder` is en empty array.
=> fix error on creating project when empty workspace is open

package-lock.json, package.json, src/handlers/setDependencyVersionHandler.ts
fix #669. use `SemVer` lib to compare dependency versions. For those who do not follow SemVer policy, correct them and then compare.
=> use SemVer lib to compare versions

package.json, package.nls.json, src/explorer/model/Dependency.ts
this pr makes three changes:
1. root dependencies do not have exclude command
2. only conflict dependencies have set-version command
3. change wording "set version to" to "resolve conflict"
=> refine right-click command entry for dependencies

package.json, src/explorer/model/Dependency.ts
this pr fixes the wrong entries of `goToDefinition` and refine context value and when-clause for future use.
format contextValue: `Dependency[+<type>]`
possible type: conflict, root
=> fix goToDefinition: refine contextValue and when-clause

src/explorer/model/MavenPlugin.ts, src/explorer/pluginInfoProvider.ts, src/utils/mavenUtils.ts, src/utils/requestUtils.ts
fix #714 
behavior change:
- on expanding "Plugins" menu, only to fetch `prefix` of all plugins from maven central metadata.
- on expanding a plugin, run `help:describe` to get precise information including `prefix` and a list of `goals`.
cache structure of plugin information:
```
{
<gid>: {
<aid>: {
prefix: <prefix>
versions: {
<version>: <goals>
}
}
}
}
```
=> boost fetching plugin prefix

src/utils/requestUtils.ts
fix #766 , which is probably caused by upstream service changes.
=> specify User-Agent when using maven search API

src/archetype/ArchetypeModule.ts, src/utils/mavenUtils.ts
Re-create PR #768 because it's accidentally closed.
Original description:
> Now that we have maven.settingsFile config, it seems natural to execute mvn with it (which I found out not.)
> Is there any concern not doing so.
=> execute mvn with maven.settingsFile

src/archetype/ArchetypeModule.ts, src/archetype/createProject/SelectArchetypeStep.ts, src/archetype/createProject/SpecifyArchetypeVersionStep.ts, src/archetype/createProject/SpecifyArtifactIdStep.ts, src/archetype/createProject/SpecifyGroupIdStep.ts, src/archetype/createProject/SpecifyTargetFolderStep.ts, src/archetype/createProject/types.ts, src/extension.ts
Can pass an `IProjectCreationMetadata` as argument to create Maven projects, which will avoid unnecessary user interactions.
=> allow external call to create project with predefined args

src/utils/mavenUtils.ts
https://github.com/microsoft/vscode-maven/issues/763#issuecomment-1008081292
=> depgraph-maven-plugin@3.3.1 fixed transitive deps

package.json
Previously the icon shows "current" type of the tree view, i.e. 'flat' button was to switch to hierarchical view, 'tree' button was to switch to flat view.
=> fix icon of view-switching buttons

src/DiagnosticProvider.ts, src/explorer/model/MavenProject.ts
Fix "Failed to find dependency" When there is a dependency conflict and the artifactId of dependency contains variables
Fixes #815
=> fix "Failed to find dependency" when findConflictRange

Troubleshooting.md
Add example error messages to background command section to help users find troubleshooting documentation when searching the repo.
=> docs: add background command error messages

package.json, package.nls.json, package.nls.zh-cn.json, package.nls.zh-tw.json, src/Settings.ts, src/explorer/model/MavenProject.ts, src/extension.ts
See https://github.com/microsoft/vscode-maven/issues/794#issuecomment-1177524076
Adding a new setting `maven.explorer.projectName` to specify format of project node name.
=> add setting for format of project node name

package-lock.json, src/explorer/model/MavenProject.ts
Fixing npe error.
```
mainThreadExtensionService.ts:80 TypeError: r is not iterable
at Object.<anonymous> (c:\Users\username\.vscode\extensions\vscjava.vscode-maven-0.36.0\dist\extension.js:2:750612)
at Generator.next (<anonymous>)
```
Root cause is `conflictNodes` can be undefined before being parsed. Now adding a getter so it's always a valid array.
=> add null check for conflictNodes

src/utils/mavenUtils.ts
It's the maven plugin we used to generate dependencies information. Some bug fixes in v3.3.2.
See #852
=> adopt fix in depgraph-maven-plugin:3.3.2

.vscode/launch.json, package.json, resources/maven-4.0.0.xsd.json, scripts/generate-maven-xsd.js, scripts/generate-maven-xsd.ts, src/completion/completionProvider.ts, src/completion/mavenXsd.ts, src/extension.ts, src/utils/lexerUtils.ts
Based on maven-4.0.0.xsd, this PR adds schema-based snippets as completion items.
For TextNode like `artifactId`, it completes as 
```
<artifactId>|<artifactId>
```
For ComplexNode like `dependencies`, it completes as 
```
<dependencies>
|
</dependencies>
```
=> add completion items based on maven.xsd

src/handlers/dependency/addDependencyHandler.ts, src/utils/editUtils.ts
Change `version` as an optional parameter when calling `maven.project.addDependency` from external.
=> allow to add dependency without specifying version

src/handlers/dependency/addDependencyHandler.ts, src/handlers/dependency/artifactUsage.ts
Re-use artifact usage data, to sort candidates from largest to smallest.
=> sort artifacts by usage

src/utils/uiUtils.ts
fix #817 
In Unix-like OS, `path` starts with "/". Directly prepending a "/" causes the error.
=> fix illegal path segment in customized uri

.azure-pipelines/ci.yml
"If you wish to enable CodeQL 3000 extension but you already onboarded to CodeQL previously though Guardian please first remove Guardian task where CodeQL is enabled."
In order to use the preferred CodeQL 3000 for ADO pipeline, I just comment the CodeQL Guardian task temporarily.
=> Recommend to use CodeQL 3000 extension for Azure DevOps

jdtls.ext/com.microsoft.java.maven.plugin/META-INF/MANIFEST.MF, jdtls.ext/com.microsoft.java.maven.plugin/build.properties, jdtls.ext/com.microsoft.java.maven.plugin/pom.xml, jdtls.ext/target.target, test/projects/maven/src/main/java/com/mycompany/app/App.java
`slf4j.api` is required by `maven-core`. the bundle is no longer required by m2e, thus we add it back manually to work it around.
=> fix: add slf4j.api back

src/archetype/createProject/SelectParentPomStep.ts, src/project/MavenProjectManager.ts
When selecting the parent pom list during "New Module", sometimes the newly added module is not recognized. This is because the maven model cache didn't store the pom contents yet and leave the artifactId is undefined.
=> Reload pom contents as needed before finding parent POMs
